SELECT A.CART_ID
FROM CART_PRODUCTS A
WHERE 1=1
AND EXISTS (SELECT 1 FROM CART_PRODUCTS WHERE CART_ID = A.CART_ID AND NAME = 'Milk')
AND EXISTS (SELECT 1 FROM CART_PRODUCTS WHERE CART_ID = A.CART_ID AND NAME = 'Yogurt')
GROUP BY A.CART_ID
ORDER BY A.CART_ID
;