SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
from APPOINTMENT A
join PATIENT B
on A.PT_NO = B.PT_NO
join DOCTOR C
on A.MDDR_ID = C.DR_ID
where 1=1
and TO_CHAR(A.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
and A.APNT_CNCL_YN = 'N'
and A.MCDP_CD = 'CS'
order by A.APNT_YMD
;
